### ISSUE TITLE
The repository should be named be renamed brainvisa_spm

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-spm#1]
@clarafischer noticed that during the migration from SVN to GitHub, this repository was renamed `brainvisa_spm` -> `brainvisa-spm`. I believe this was a mistake, as all other BrainVISA projects use the hyphen `-` for the licence suffix (`-free`, `-gpl`, `-nonfree`, or `-private`). We can fix this by:

1. Renaming this repository on GitHub. GitHub automatically puts a redirection in place, so clients that use the old URL will still be able to access the respository
2. Renaming the project in [components_definition.py](https://github.com/brainvisa/brainvisa-cmake/blob/5.0/python/brainvisa/maker/components_definition.py)

@brainvisa/admin do you agree?

**Comment by denisri** [comment]
If you prefer like this, I'm OK. But in a general way we haven't succeeded at any point in naming our projects consistently ;)
Look:
```
brainvisa-share
brainvisa-spm or brainvisa_spm
brainvisa-cmake
brainvisa_freesurfer
casa-distro
cortical_surface
morpho-deepsulci
morphologist-ui
populse_db
nuclear_imaging
longitudinal_pipelines
highres-cortex
```
so it's a mess in any case :/

**Comment by ylep** [comment]
> so it's a mess in any case :/

Oh well, you ’re right. Unless this poses a specific issue (@clarafischer ?) we should probably keep it like this...

**Comment by denisri** [comment]
Aa people like, personally I don't mind...
